version: 0.1
            
phases:

  pre_build: 
    commands:

      # could add a linter step here...

      # Run all tests included with our application
      - cd backend
      - go test

  build:
    commands:
      - cd backend
      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    - buildspec.yml
